kind: Namespace
apiVersion: v1
metadata:
  name: {{ .Values.namespace }}

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: rolling-pin
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rolling-pin
  template:
    metadata:
      labels:
        app: rolling-pin
    spec:
      containers:
        - name: rolling-pin
          image: {{ .Values.container.image }}:{{ .Values.container.tag }}
          imagePullPolicy: {{ .Values.container.image_pull_policy }}
          command: [{{ join ", " .Values.container.command }}]
          env: {{- range .Values.container.env }}
            - name: {{ .name }}
              value: "{{ .value }}"
          {{- end }}
          ports:
            - containerPort: {{ .Values.container.port }}
          livenessProbe:
            httpGet:
              path: /healthz/live
              port: {{ .Values.container.port }}
            initialDelaySeconds: 5
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /healthz/ready
              port: {{ .Values.container.port }}
            initialDelaySeconds: 5
            timeoutSeconds: 1
          volumeMounts:
            - name: storage
              mountPath: /mnt/storage
            - name: repo
              mountPath: /home/ubuntu/rolling-pin
      volumes:
        - name: storage
          hostPath:
            path: {{ .Values.container.storage_volume }}
            type: Directory
        - name: repo
          hostPath:
            path: {{ .Values.container.repo }}
            type: Directory

---
kind: Service
apiVersion: v1
metadata:
  name: rolling-pin
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: rolling-pin
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}

---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: ingress
  namespace: {{ .Values.namespace }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/rewrite-target: /rolling-pin
spec:
  rules:
    - http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: rolling-pin
                port:
                  number: {{ .Values.service.port }}
