namespace: rolling-pin

container:
  image: rolling-pin
  tag: latest
  repo: /mnt/repos/rolling-pin
  storage_volume: /mnt/storage
  port: 8080
  image_pull_policy: IfNotPresent
  command:
    [
      "python3.7",
      "/home/ubuntu/rolling-pin/python/rolling_pin/server/app.py",
    ]

service:
  port: 80
