namespace: rolling-pin

organization: k8s

container:
  image: k3d-dev-registry:5100/rolling-pin
  tag: dev
  repo: /mnt/repos/rolling-pin
  storage_volume: /mnt/storage
  port: 8080
  image_pull_policy: IfNotPresent
  command:
    [
      "python3.7",
      "/home/ubuntu/rolling-pin/python/rolling-pin/server/app.py",
    ]
  env:
    - name: REPO_ENV
      value: "True"

service:
  port: 80

ingress:
  path: /rolling-pin
